### ISSUE TITLE
Web3API Namespaces

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/toolchain#47]
NOTE: This is an optional feature. Specifying an API w/o a namespace should still work, and the root path should be assumed.

**Manifest Change:**
```yaml
apis:
  - namespace: "foo"
    schema:
      - file: ./src/foo/schema.graphql
    mutation:
      language: wasm/assemblyscript
      file: ./src/foo/mutation/index.ts
    query:
      language: wasm/assemblyscript
      file: ./src/foo/query/index.ts
  - namespace: "bar"
    schemas:
      - file: ./src/bar/mutation/schema.graphql
      - file: ./src/bar/query/schema.graphql
    mutation:
      language: wasm/assemblyscript
      file: ./src/bar/mutation/index.ts
    query:
      language: wasm/assemblyscript
      file: ./src/bar/query/index.ts
```

**Client Change:**
```typescript
client.query({
  uri: "example.eth/foo"
  query: gql`
    mutation {
      setData(
        address: "0x123..."
        value: 5
      )
    }`
})
```
